"""CSV logger for telemetry frames.

The logger lives downstream of :class:`FrameBus` — it enables the bus's
optional CSV queue, then drains it on a dedicated :class:`threading.Thread`
that writes rows to disk and ``flush()``es periodically. The polling
worker never blocks on file I/O: bounded-queue backpressure drops the
oldest row when disk hiccups, so the SHM read cadence stays exact.

Schema is generated by introspecting :mod:`dataclasses.fields` on
:class:`TelemetryFrame`, :class:`EngineData`, :class:`InputsData`, and
:class:`WheelData`. Adding a new scalar field to any of those dataclasses
automatically becomes a new CSV column the next time the user starts a
session — no schema-maintenance step.

Heavy list-typed fields (``torque_curve_nm``, ``temp_curve_pts``) are
skipped: those are per-car static tables, not per-frame telemetry, and
they'd repeat identical rows of values that bloat the file with no signal.
"""
from __future__ import annotations

import csv
import dataclasses
import queue
import threading
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

from .frame_bus import FrameBus
from .paths import logs_dir as _resolve_logs_dir
from .telemetry import EngineData, InputsData, TelemetryFrame, WHEEL_IDS, WheelData


# Fields whose value is a list/dict and would explode the column count
# without giving useful per-frame signal. Per-car static tables, not
# per-frame telemetry.
_SKIP_FIELDS: frozenset[str] = frozenset({
    "torque_curve_nm",
    "temp_curve_pts",
})

# How often the writer thread flushes to disk. At 60 Hz this is roughly
# once a second; at 250 Hz once every ~0.25 s. Trades worst-case data
# loss on a hard kill for write-amplification: a hard kill mid-session
# costs at most this many rows. csv.writer + a buffered file handle
# means each row is in OS cache immediately; the flush just guarantees
# the user agent (Excel etc.) sees it without closing the file.
_FLUSH_EVERY_N_ROWS = 60


def _logs_dir() -> Path:
    """Resolved by :mod:`overlay.paths` — next to the bundled ``.exe``
    in release builds, in the current working directory during dev runs."""
    return _resolve_logs_dir()


def _flatten_dataclass(prefix: str,
                       obj: Any) -> list[tuple[str, Any]]:
    """Return ``[(column_name, value), …]`` for one nested dataclass.

    Tuples / lists of scalars get index-suffixed columns
    (``damage[0]``…``damage[4]``); list-of-tuples fields named in
    :data:`_SKIP_FIELDS` are omitted entirely.
    """
    out: list[tuple[str, Any]] = []
    for f in dataclasses.fields(obj):
        if f.name in _SKIP_FIELDS:
            continue
        value = getattr(obj, f.name)
        col = f"{prefix}.{f.name}" if prefix else f.name
        if isinstance(value, (list, tuple)) and value and not isinstance(value[0], (list, tuple)):
            for i, item in enumerate(value):
                out.append((f"{col}[{i}]", item))
        else:
            out.append((col, value))
    return out


def _frame_columns(frame: TelemetryFrame) -> list[str]:
    """Compute the full CSV header from one TelemetryFrame instance."""
    cols: list[str] = ["ts_unix", "ts_mono"]
    cols.extend(c for c, _ in _flatten_dataclass("engine", frame.engine))
    cols.extend(c for c, _ in _flatten_dataclass("inputs", frame.inputs))
    for wid in WHEEL_IDS:
        cols.extend(c for c, _ in _flatten_dataclass(
            f"wheels.{wid}", frame.wheels[wid]))
    return cols


def _frame_row(frame: TelemetryFrame, ts_unix: float, ts_mono: float) -> list[Any]:
    """Project one TelemetryFrame into a list of column values in the
    same order :func:`_frame_columns` produced."""
    row: list[Any] = [f"{ts_unix:.6f}", f"{ts_mono:.6f}"]
    for _, v in _flatten_dataclass("engine", frame.engine):
        row.append(v)
    for _, v in _flatten_dataclass("inputs", frame.inputs):
        row.append(v)
    for wid in WHEEL_IDS:
        for _, v in _flatten_dataclass(f"wheels.{wid}", frame.wheels[wid]):
            row.append(v)
    return row


class CsvLogger:
    """Owns a single CSV file + a writer thread.

    The logger is started / stopped from the UI thread; the actual disk
    I/O happens on the writer thread so a stalled drive can never block
    the polling worker. Backpressure is handled at the bus level —
    when the queue fills, the bus drops the oldest snapshot rather than
    blocking either thread.
    """

    def __init__(self, bus: FrameBus) -> None:
        self._bus = bus
        self._thread: Optional[threading.Thread] = None
        self._stop_event = threading.Event()
        self._path: Optional[Path] = None
        # Latched while writer thread is running; UI inspects via
        # :meth:`is_active`.
        self._active = False

    def is_active(self) -> bool:
        return self._active

    def current_path(self) -> Optional[Path]:
        return self._path

    @staticmethod
    def logs_dir() -> Path:
        return _logs_dir()

    def start(self, source_name: str) -> Path:
        """Open a new CSV file and start the writer thread.

        ``source_name`` (e.g. ``"ac1"``) lands in the filename so the
        user can tell sessions apart at a glance. Returns the path.
        """
        if self._active:
            return self._path or _logs_dir()
        stamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
        safe = "".join(c if c.isalnum() or c in "._-" else "_"
                       for c in source_name)
        self._path = _logs_dir() / f"{stamp}_{safe}.csv"
        # The bus's queue is opened here — the polling worker only pays
        # the put_nowait cost while logging is active.
        self._stop_event.clear()
        q = self._bus.enable_csv()
        self._active = True
        self._thread = threading.Thread(
            target=self._run, args=(q,), name="csv-writer", daemon=True)
        self._thread.start()
        return self._path

    def stop(self) -> None:
        """Signal the writer thread to drain + flush + close, then join."""
        if not self._active:
            return
        self._stop_event.set()
        # Stop publishing first so the queue can drain to empty and the
        # writer's blocking get() unblocks via the sentinel below.
        self._bus.disable_csv()
        t = self._thread
        if t is not None:
            # Wake the writer if it's blocked on get() with an empty queue.
            try:
                if self._bus.csv_queue is None:
                    # Already disabled — the writer's queue reference is
                    # still valid (it captured it at start); drop a None
                    # sentinel on it.
                    pass
            except Exception:
                pass
            t.join(timeout=2.0)
        self._thread = None
        self._active = False

    def _run(self, q: "queue.Queue[TelemetryFrame]") -> None:
        # Build header lazily from the first frame so we capture the
        # actual published shape (post-source dataclass-default fills).
        rows_since_flush = 0
        # newline="" required by the csv module on Windows to keep it
        # from inserting an extra \r between rows.
        with open(self._path, "w", newline="", encoding="utf-8",
                  buffering=8192) as fp:
            writer = csv.writer(fp)
            header_written = False
            while not self._stop_event.is_set() or not q.empty():
                try:
                    frame = q.get(timeout=0.25)
                except queue.Empty:
                    continue
                if not header_written:
                    writer.writerow(_frame_columns(frame))
                    header_written = True
                writer.writerow(_frame_row(frame, time.time(), time.monotonic()))
                rows_since_flush += 1
                if rows_since_flush >= _FLUSH_EVERY_N_ROWS:
                    fp.flush()
                    rows_since_flush = 0
            fp.flush()
