"""Generate ``sources/acc_cars.py`` from the official ACC SHM documentation.

ACC's shared memory publishes a *raw* brake bias; the in-car dash adds a
per-car offset before showing it to the driver, so the overlay's readout
is off by up to 21 points depending on the car. Kunos documents the
offsets — along with per-car steering lock and max RPM — in the appendices
of the shared-memory PDF we already ship in ``resources/docs/acc``.

Rather than parse a PDF at runtime (and take a pypdf dependency into the
bundle), this tool extracts the tables once and writes a plain Python
module. Re-run it when Kunos publishes a documentation update:

    python tools/gen_acc_car_table.py

Requires ``pypdf`` (a dev dependency, see requirements-dev.txt).
"""
from __future__ import annotations

import os
import re
import sys

try:
    import pypdf
except ImportError:  # pragma: no cover - dev-only tool
    sys.exit("pypdf is required: pip install -r requirements-dev.txt")


_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PDF = os.path.join(_ROOT, "resources", "docs", "acc",
                   "ACCSharedMemoryDocumentationV1.8.12.pdf")
OUT = os.path.join(_ROOT, "src", "live_telemetry_evo", "sources", "acc_cars.py")

# Appendix 2 maps display name -> the Kunos id the SHM publishes as
# ``static.carModel``; 4/5/7 are keyed by the same display names.
APPENDIX_IDS, APPENDIX_BIAS, APPENDIX_STEER, APPENDIX_RPM = 2, 4, 5, 7


def _pages_text(path: str) -> list[str]:
    reader = pypdf.PdfReader(path)
    return [page.extract_text() or "" for page in reader.pages]


def _appendix_lines(texts: list[str], number: int) -> list[str]:
    """Lines belonging to one appendix — from its heading to the next."""
    out: list[str] = []
    active = False
    for text in texts:
        for line in text.splitlines():
            heading = re.match(r"\s*Appendix (\d+)", line)
            if heading:
                active = int(heading.group(1)) == number
                continue
            if active:
                out.append(line.rstrip())
    return out


def _parse_id_table(lines: list[str]) -> dict[str, str]:
    """``Name  kunos_id`` rows — the id is the trailing snake_case token."""
    rows: dict[str, str] = {}
    for line in lines:
        match = re.match(r"\s*(.+?)\s+([a-z0-9]+(?:_[a-z0-9]+)+)\s*$", line)
        if match and not match.group(1).strip().lower().startswith("name"):
            rows[match.group(1).strip()] = match.group(2)
    return rows


def _parse_value_table(lines: list[str]) -> dict[str, float]:
    """``Name  <number>`` rows."""
    rows: dict[str, float] = {}
    for line in lines:
        match = re.match(r"\s*(.+?)\s+(-?\d+(?:\.\d+)?)\s*$", line)
        if match and not match.group(1).strip().lower().startswith("name"):
            rows[match.group(1).strip()] = float(match.group(2))
    return rows


def _norm(name: str) -> str:
    """Loose join key. The PDF spells the same car differently between
    appendices ('BMW M4 vGT3 2021' in App 2, 'BMW M4 GT3' in App 4), so we
    drop model years and non-alphanumerics before matching."""
    key = name.lower()
    key = re.sub(r"\b(19|20)\d{2}\b", "", key)
    key = re.sub(r"\bv?gt3\b", "gt3", key)
    return re.sub(r"[^a-z0-9]+", "", key)


def build_table() -> dict[str, tuple[float, float, float]]:
    texts = _pages_text(PDF)
    ids = _parse_id_table(_appendix_lines(texts, APPENDIX_IDS))
    bias = {_norm(k): v for k, v
            in _parse_value_table(_appendix_lines(texts, APPENDIX_BIAS)).items()}
    steer = {_norm(k): v for k, v
             in _parse_value_table(_appendix_lines(texts, APPENDIX_STEER)).items()}
    rpm = {_norm(k): v for k, v
           in _parse_value_table(_appendix_lines(texts, APPENDIX_RPM)).items()}

    table: dict[str, tuple[float, float, float]] = {}
    unjoined: list[str] = []
    for name, car_id in sorted(ids.items()):
        key = _norm(name)
        if key not in bias:
            unjoined.append(name)
            continue
        table[car_id] = (bias[key], steer.get(key, 0.0), rpm.get(key, 0.0))
    if unjoined:
        print(f"WARNING: no bias row for {len(unjoined)} cars: {unjoined}")
    return table


HEADER = '''"""Per-car ACC constants from the official shared-memory documentation.

GENERATED by ``tools/gen_acc_car_table.py`` from
``resources/docs/acc/ACCSharedMemoryDocumentationV1.8.12.pdf`` —
edit the generator, not this file.

Keys are the Kunos car ids ACC publishes as ``static.carModel``
(Appendix 2). Values, in order:

* ``bias_offset`` — percentage points the in-car dash adds to the raw
  ``physics.brakeBias`` before displaying it (Appendix 4). Always
  negative; ranges from -5 to -21. Without it the overlay reads up to 21
  points higher than the dash the driver is looking at.
* ``steer_lock`` — total steering lock in degrees (Appendix 5). Not used
  yet: ``physics.steerAngle`` is already normalised -1..1, so this is only
  useful for converting that back into degrees of wheel rotation.
* ``max_rpm`` — redline (Appendix 7). Redundant with ``static.maxRpm``,
  kept for cross-checking cars whose static block reads zero.
"""
from __future__ import annotations


# car id -> (bias_offset, steer_lock, max_rpm)
_CARS: dict[str, tuple[float, float, float]] = {
'''

FOOTER = '''}


def dash_bias_offset(car_model: str) -> float:
    """Percentage points to add to the raw brake bias for this car.

    Returns 0.0 for an unknown car (a new DLC we have no documentation
    for yet), which leaves the raw value untouched — the previous
    behaviour, and the only safe default.
    """
    entry = _CARS.get((car_model or "").strip())
    return entry[0] if entry else 0.0


def steering_lock_deg(car_model: str) -> float:
    """Total steering lock in degrees, or 0.0 when unknown."""
    entry = _CARS.get((car_model or "").strip())
    return entry[1] if entry else 0.0


def documented_max_rpm(car_model: str) -> float:
    """Documented redline, or 0.0 when unknown."""
    entry = _CARS.get((car_model or "").strip())
    return entry[2] if entry else 0.0


def known_cars() -> list[str]:
    """Every car id the documentation covers."""
    return sorted(_CARS)
'''


def main() -> int:
    if not os.path.isfile(PDF):
        sys.exit(f"documentation PDF not found: {PDF}")
    table = build_table()
    if not table:
        sys.exit("no rows parsed — has the PDF layout changed?")
    lines = [HEADER]
    for car_id, (bias, steer, rpm) in sorted(table.items()):
        lines.append(f'    "{car_id}": ({bias:g}, {steer:g}, {rpm:g}),\n')
    lines.append(FOOTER)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("".join(lines))
    print(f"wrote {OUT} with {len(table)} cars")
    return 0


if __name__ == "__main__":
    sys.exit(main())
