"""Per-car ACC constants from the official shared-memory documentation.

GENERATED by ``tools/gen_acc_car_table.py`` from
``resources/docs/acc/ACCSharedMemoryDocumentationV1.8.12.pdf`` —
edit the generator, not this file.

Keys are the Kunos car ids ACC publishes as ``static.carModel``
(Appendix 2). Values, in order:

* ``bias_offset`` — percentage points the in-car dash adds to the raw
  ``physics.brakeBias`` before displaying it (Appendix 4). Always
  negative; ranges from -5 to -21. Without it the overlay reads up to 21
  points higher than the dash the driver is looking at.
* ``steer_lock`` — total steering lock in degrees (Appendix 5). Not used
  yet: ``physics.steerAngle`` is already normalised -1..1, so this is only
  useful for converting that back into degrees of wheel rotation.
* ``max_rpm`` — redline (Appendix 7). Redundant with ``static.maxRpm``,
  kept for cross-checking cars whose static block reads zero.
"""
from __future__ import annotations


# car id -> (bias_offset, steer_lock, max_rpm)
_CARS: dict[str, tuple[float, float, float]] = {
    "alpine_a110_gt4": (-15, 360, 6450),
    "amr_v12_vantage_gt3": (-7, 320, 7750),
    "amr_v8_vantage_gt3": (-7, 320, 7250),
    "amr_v8_vantage_gt4": (-20, 320, 7000),
    "audi_r8_gt4": (-15, 360, 8650),
    "audi_r8_lms": (-14, 360, 8650),
    "audi_r8_lms_evo": (-14, 360, 8650),
    "audi_r8_lms_evo_ii": (-14, 360, 8650),
    "bentley_continental_gt3_2016": (-7, 320, 7400),
    "bentley_continental_gt3_2018": (-7, 320, 7400),
    "bmw_m2_cs_racing": (-17, 180, 7520),
    "bmw_m4_gt3": (-14, 270, 7000),
    "bmw_m4_gt4": (-22, 246, 7600),
    "bmw_m6_gt3": (-15, 283, 7100),
    "chevrolet_camaro_gt4r": (-18, 360, 7500),
    "ferrari_488_challenge_evo": (-13, 240, 8000),
    "ferrari_488_gt3": (-17, 240, 7300),
    "ferrari_488_gt3_evo": (-17, 240, 7600),
    "ginetta_g55_gt4": (-18, 360, 7200),
    "honda_nsx_gt3": (-14, 310, 7500),
    "honda_nsx_gt3_evo": (-14, 310, 7650),
    "jaguar_g3": (-7, 360, 8750),
    "ktm_xbow_gt4": (-20, 290, 6500),
    "lamborghini_gallardo_rex": (-14, 360, 8650),
    "lamborghini_huracan_gt3": (-14, 310, 8650),
    "lamborghini_huracan_gt3_evo": (-14, 310, 8650),
    "lamborghini_huracan_st": (-14, 310, 8650),
    "lamborghini_huracan_st_evo2": (-14, 310, 8650),
    "lexus_rc_f_gt3": (-14, 320, 7750),
    "maserati_mc_gt4": (-15, 450, 7000),
    "mclaren_570s_gt4": (-9, 240, 7600),
    "mclaren_650s_gt3": (-17, 240, 7500),
    "mclaren_720s_gt3": (-17, 240, 7700),
    "mercedes_amg_gt3": (-14, 320, 7900),
    "mercedes_amg_gt3_evo": (-14, 320, 7600),
    "mercedes_amg_gt4": (-20, 246, 7000),
    "nissan_gt_r_gt3_2017": (-15, 320, 7500),
    "nissan_gt_r_gt3_2018": (-15, 320, 7500),
    "porsche_718_cayman_gt4_mr": (-20, 400, 7800),
    "porsche_991_gt3_r": (-21, 400, 9250),
    "porsche_991ii_gt3_cup": (-5, 400, 8500),
    "porsche_991ii_gt3_r": (-21, 400, 9250),
    "porsche_992_gt3_cup": (-5, 270, 8750),
}


def dash_bias_offset(car_model: str) -> float:
    """Percentage points to add to the raw brake bias for this car.

    Returns 0.0 for an unknown car (a new DLC we have no documentation
    for yet), which leaves the raw value untouched — the previous
    behaviour, and the only safe default.
    """
    entry = _CARS.get((car_model or "").strip())
    return entry[0] if entry else 0.0


def steering_lock_deg(car_model: str) -> float:
    """Total steering lock in degrees, or 0.0 when unknown."""
    entry = _CARS.get((car_model or "").strip())
    return entry[1] if entry else 0.0


def documented_max_rpm(car_model: str) -> float:
    """Documented redline, or 0.0 when unknown."""
    entry = _CARS.get((car_model or "").strip())
    return entry[2] if entry else 0.0


def known_cars() -> list[str]:
    """Every car id the documentation covers."""
    return sorted(_CARS)
